### ISSUE TITLE
No such file or directory: './data/word_embedding.pkl

### ISSUE THREAD

**Issue by rentonliu** [baidu/Dialogue#1]
I got this error message when I try to reproduce the test result using the pretrained model. However, the pretrained word embedding model is missing. 

```bash
loading word emb init
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    model = net.Net(conf)
  File "./models/net.py", line 22, in __init__
    self._word_embedding_init = pickle.load(open(self._conf['word_emb_init'], 'rb'))
IOError: [Errno 2] No such file or directory: './data/word_embedding.pkl'

```

my question is where can i get ./data/word_embedding.pkl ? 
Thank you

**Comment by rentonliu** [comment]
Oh, I find it under `data/{ubuntu, douban}/wordembedding.pkl`
thanks!

**Comment by omi982** [comment]
where I can get this 'data.zip' FILE plz help @xyzhou-puck @zhibo-liu
