### ISSUE TITLE
Direct link to download data

### ISSUE THREAD

**Issue by basma-b** [baidu/Dialogue#10]
Please can you provide direct link to download data ? I've to register via your link and it's impossible.

**Comment by luluxing3** [comment]
Hi basma-b,

The link of data in Baidu Netdisk is 
    https://pan.baidu.com/s/1hakfuuwdS8xl7NyxlWzRiQ

And alternative link in dropbox is
    https://www.dropbox.com/s/h7g3iy9vuxlbtar/data.zip?dl=0

**Comment by basma-b** [comment]
Thank you !

**Comment by norbertryc** [comment]
@luluxing3 Same problem with pretrained models - it is complicated for people out of China to get files from baidu. Could you provide dropbox link to models?
