### ISSUE TITLE
oov problem in training

### ISSUE THREAD

**Issue by YFwang1992** [baidu/Dialogue#12]
Hi 
i want to retrain the model in douban dataset
but i got oov error
my gpu is Tesla M40(11448MiB)
mem free 141G
anything i can do except change batch_size?

**Comment by xyzhou-puck** [comment]
Hi,

You can save your memory by using float16 instead of float32, put different variables on different GPUs, or reduce the number of self-attention-layers. Also, you can consider using Baidu Yun, there may be some discounts for new users.

Xiangyang
