### ISSUE TITLE
不太懂test的结果。

### ISSUE THREAD

**Issue by zysNLP** [baidu/Dialogue#15]
你好，我把main文件里的调用改为test.test(conf, model)。参数的设置如下：
conf = {
    "data_path": "./data/douban/data.pkl",
    "save_path": "./output/douban/DAM_test/",
    "word_emb_init": "./data/douban/word_embedding.pkl",
    #"init_model": None, # None for train
    "init_model": "./output/douban/DAM/DAM.ckpt", #should be set for test

    "rand_seed": None, 

    "drop_dense": None,
    "drop_attention": None,

    "is_mask": True,
    "is_layer_norm": True,
    "is_positional": False,  

    "stack_num": 5,  
    "attention_type": "dot",

    "learning_rate": 1e-3,
    "vocab_size": 172130, #434512
    "emb_size": 200,
    "batch_size": 32, #200 for test

    "max_turn_num": 9,  
    "max_turn_len": 50, 

    "max_to_keep": 1,
    "num_scan_data": 2,
    "_EOS_": 1, #28270 for douban data
    "final_n_class": 1,
}

得到的程序在shell中的运行结果：
sucess init ./output/douban/DAM/DAM.ckpt
starting test
2019-01-16 15:50:51
finish test
2019-01-16 15:51:39
finish evaluation
2019-01-16 15:51:39
我观察到，在我的save_path中得到了两个文件：result.test和score.test。
其中，result.test数据为：
0.542857142857
0.133834586466
0.24962406015
0.565413533835
请问这个结果代表什么呢？后三个数似乎指的是原文中的R10@1、R10@2和R10@5，是这样么？

**Comment by xyzhou-puck** [comment]
你好，分别是：R2@1, R10@1, R10@2, R10@5

**Comment by zysNLP** [comment]
谢谢！

**Comment by Sjzwind** [comment]
你好，我测试得到的也是你贴的结果，这个数据和output中的result以及论文中的结果有太大的差距，请问你了解这是什么情况吗。。
