### ISSUE TITLE
问下怎么应用？

### ISSUE THREAD

**Issue by zysNLP** [baidu/Dialogue#17]
问下模型训练好了以后怎么用在问答系统中，就是说怎么根据模型做出一个人机对话系统？当我输入一句话以后，模型给我输出一句话？可以发一下应用模块的代码么？

**Comment by xyzhou-puck** [comment]
Hi，如果是中文项目，可以使用https://ai.baidu.com/unit/home，我们在上面有一个简易版的chatbot，可以直接调用，如果对效果有比较强的需求，可以联系UNIT平台的客服人员。

**Comment by zysNLP** [comment]
请问怎么联系客服人员呢

**Comment by xyzhou-puck** [comment]
QQ支持群：805312106

百度Hi支持群：1617262

客服电话：4008-777-818
