### ISSUE TITLE
layers.py内容好像不太对

### ISSUE THREAD

**Issue by zysNLP** [baidu/Dialogue#20]
你好，我在阅读您的代码时，发现在utils下的layers.py文件中，第285及以后的各行，都是if add_relu:conv_0 = tf.nn.elu(conv_0) 也就是您定义的变量是是否增加relu——add_relu，而实际上执行的是是否增加elu。据我所知，这两个函数应该是不一样的，您是否考虑修改add_relu变量名或者修改elu呢？

**Comment by xyzhou-puck** [comment]
@luluxing3

**Comment by zysNLP** [comment]
> @luluxing3

什么意思？

**Comment by luluxing3** [comment]
The relu and elu are two different activation functions. But the experimental results are similar using either relu or elu. It is better to correct the variable name or activation function to make them match. 
Thanks.

**Comment by zysNLP** [comment]
Thank you very much!
