### ISSUE TITLE
what does the "corpus_file text_file topic_file index_file 1 1" mean? 

### ISSUE THREAD

**Issue by zysNLP** [baidu/Dialogue#25]
In the model "knowledge-driven dialogue/generative_pytorch_version/"
In the readme.rd:
Step 1: Preprocess
preprocess all the data using in model training and testing stage with the following commands

    python ./tools/convert_conversation_corpus_to_model_text.py corpus_file text_file topic_file index_file 1 1

what does the "corpus_file text_file topic_file index_file 1 1" mean? where are the three files?

**Comment by xyzhou-puck** [comment]
Hi,

This repository (knowledge-driven dialogue) is for our dialogue competition with CCF and CIPS (https://zhi.co/ai/5061.html), we will release more information about it soon.

**Comment by zysNLP** [comment]
All right,Thank you very much!
