### ISSUE TITLE
vocabulary size of douban data

### ISSUE THREAD

**Issue by Sjzwind** [baidu/Dialogue#27]
Hi,
1. what's the min count when training douban data word embedding，as there are more than 30w+ vocab in douban data, do you test the impact of different vocb size to this model.
2. Is there significant influence whether or not to set word embedding trainable?

Thanks.

**Comment by xyzhou-puck** [comment]
Hi,

1. we get the embedding using our in-house word-embedding training tool. I remember the min count is one probably.  
2. Yes, because the embedding you got may not be ideal.

Xingyang

**Comment by Sjzwind** [comment]
Could you confirm the min count is one? Because when I set one using word2vec in gensim, there are exactly 30w+ vocab size for douban data, and the part pre-trained word embedding is what I am confused.

Thanks.
