### ISSUE TITLE
豆瓣数据集训练有问题

### ISSUE THREAD

**Issue by WilliamJustin** [baidu/Dialogue#30]
请问一下，我在源程序上没有做改动运行，python2和tensorflow1.2.1，然后第一次保存模型时evaluate的结果MAP和MRR都达到了0.9以上，之后还会更高，逼近0.99，这肯定是有问题的，这会是什么问题导致的呢

**Comment by WilliamJustin** [comment]
是不是得自己把验证集正负比例调到1:9啊，Orz

**Comment by xyzhou-puck** [comment]
豆瓣的evaluator跟Ubuntu的不太一样，代码里有注明，建议先check一下源码

**Comment by WilliamJustin** [comment]
0.9以上是因为那是验证集，尴尬。。。
