### ISSUE TITLE
In predicting time, do we need to compute all the sentence in the dataset?

### ISSUE THREAD

**Issue by guotong1988** [baidu/Dialogue#35]
Any sugguestion to accelerate?
Thank you!

这个多轮模型预测用的时候，是不是要把库里所有候选都算一遍？
@xyzhou-puck

**Comment by xyzhou-puck** [comment]
Hi，建议可以搞多层级 rank，速度快的模型粗排，效果好的精排。另外推荐您使用我们基于 ernie的对话匹配模型：https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/dialogue_model_toolkit/dialogue_general_understanding

**Comment by guotong1988** [comment]
谢谢！

**Comment by guotong1988** [comment]
请问下有哪些速度快的粗排模型呢

**Comment by xyzhou-puck** [comment]
可以考虑使用 paddleNLP 里面的 simnet模型，训练一个 context-response matching model。
