### ISSUE TITLE
需要自己写数据预处理的代码？

### ISSUE THREAD

**Issue by guotong1988** [baidu/Dialogue#36]
没有数据转成pickle的代码吧？谢谢！
@xyzhou-puck

**Comment by xyzhou-puck** [comment]
您好，这个数据是通过 hack SMN 的 code 得到的。

**Comment by guotong1988** [comment]
谢谢！

**Comment by yangpeiyi** [comment]
您好，请问data.pkl里面，
`data['c'][0]=[28080,` 138854, 180037, ..., 91963]`
这些数字的具体含义是什么？
我的理解是vocabulary.txt里对应单词的索引，但是有些数字（如180037）完全超出索引范围了...
谢谢您的回答！
