### ISSUE TITLE
有没尝试用过BERT的tokenizer方式？

### ISSUE THREAD

**Issue by guotong1988** [baidu/Dialogue#39]
vocab只有2W-3W个词

**Comment by xyzhou-puck** [comment]
您好，BERT 的 tokenizer 更好一些，感觉可以尝试。不过我更倾向于直接用 BERT，因为基本上很多地方很类似。

**Comment by guotong1988** [comment]
就是[CLS],context,[SEP],response,[SEP]这样？

**Comment by xyzhou-puck** [comment]
可以尝试使用他的 tokenizer 吧

**Comment by guotong1988** [comment]
> 不过我更倾向于直接用 BERT，因为基本上很多地方很类似。

？？？

**Comment by guotong1988** [comment]
谢谢！

**Comment by guotong1988** [comment]
有BERT的tokenizer但是没有对应的词向量。。。
