### ISSUE TITLE
请问下多轮和单轮的兼容问题有什么好的策略吗？

### ISSUE THREAD

**Issue by guotong1988** [baidu/Dialogue#40]
@xyzhou-puck 多谢！

比如第二轮时候，可以走多轮，也可以走单轮，这时怎么办。

**Comment by guotong1988** [comment]
貌似，有两个模型，一个多轮模型和一个单轮模型，都走多轮的就可

**Comment by xyzhou-puck** [comment]
嗯，在大数据上训练出来的经验，一般来说，都走单轮即可。不过建议还是具体问题，具体分析。
