### ISSUE TITLE
tf.einsum('biks,bjks->bijs', t_a_r, r_a_t)

### ISSUE THREAD

**Issue by yiyele** [baidu/Dialogue#44]
想请问一下，这个公式的含义是什么？有没有相关的资料可以参考。多谢

**Comment by xyzhou-puck** [comment]
https://zhuanlan.zhihu.com/p/30683752

**Comment by yiyele** [comment]
知道这个公式，但是这么处理有什么依据呢？就是矩阵matmul(A,B)作为相似度么？？

**Comment by xyzhou-puck** [comment]
是的，主要是用来衡量相似度。
