### ISSUE TITLE
Where is CUDA_VISIBLE_DEVICES=0 ../attention_SMN/python/bin/python main.py？

### ISSUE THREAD

**Issue by Crystalsudo** [baidu/Dialogue#46]
Hi, I would like to ask about which place this attention_SMN lies in.
#! /bin/bash
CUDA_VISIBLE_DEVICES=0 ../attention_SMN/python/bin/python main.py
Thank you very much and look forward to your reply!

**Comment by xyzhou-puck** [comment]
Hi,

The `../attention_SMN/python/bin/python` is the bin file of python, you can replace this with python.

Sorry for this bug and we will fix it.

Xiangyang

**Comment by Crystalsudo** [comment]
Ok, got it ! Thx！
