### ISSUE TITLE
Preprocessing scripts

### ISSUE THREAD

**Issue by basma-b** [baidu/Dialogue#5]
Can you share please the scripts you used to preprocess data and also to train word embeddings ?

**Comment by xyzhou-puck** [comment]
We directly used the released dataset from sequential-matching-network (Wu et al., 2017), thus there is no preprocessing phase in our experiments. 

We pre-train word-embeddings using a word2vec toolkit in c++, I can hardly find the script we used to pre-train word-embeddings, maybe the following command can help you:

./bin/word2vec -train $train_dat -output "$train_dat.w2v" -debug 2 -size 200 -window 10 -sample 1e-4 -negative 25 -hs 0 -binary 1 -cbow 1 -min-count 1
