### ISSUE TITLE
The format of the input_example about "udc" task.

### ISSUE THREAD

**Issue by bringtree** [baidu/Dialogue#52]
https://github.com/baidu/Dialogue/blob/8fe0e64644b635dc44261e71db71cb9e576953e0/DGU/dgu/reader.py#L769-L774
Hello!
    When the task is "udc",  does the context been seen as a single sentence rather than multi sentences?

**Comment by xyzhou-puck** [comment]
yes, multiple context utterances are token as a single sentence in udc.
