### ISSUE TITLE
what is the usage for tt_turns_len placeholder in the model

### ISSUE THREAD

**Issue by szho42** [baidu/Dialogue#8]
Hi, 
A short question:
when going through the code, wondering the reason why the placeholder, tt_turns_len, is NOT used in the model, after being defined?

cheers

**Comment by luluxing3** [comment]
Sorry for late reply.
The placeholder, tt_turns_len, is not used indeed. You can just delete it.

**Comment by szho42** [comment]
@luluxing3 thanks for your reply. it is really great that your model works in our case.
